### ISSUE TITLE
Add server side rendering instructions in docs 

### ISSUE THREAD

**Issue by remojansen** [remojansen/redux-bootstrap#9]
## Expected Behavior
Server side rendering supported in docs.

## Current Behavior
Server side rendering supported not available in docs.

## Possible Solution
Use instructions at [redux docs](http://redux.js.org/docs/recipes/ServerRendering.html).

**Comment by jokeyrhyme** [comment]
I'd be especially interested to see documentation on how to integrate this with [ryanflorence/react-project](https://github.com/ryanflorence/react-project), which offers browser and server rendering.

**Comment by jokeyrhyme** [comment]
Blocked by #10 ?

**Comment by remojansen** [comment]
Hi @jokeyrhyme you are right #10 needs to be implemented first.

**Comment by jokeyrhyme** [comment]
We're probably going to need an option to stop `bootstrap()` from automatically rendering to the container element in the DOM, because there won't be a container element or a DOM.

What if BoostrapOptions had an optional "render" property, so that a consumer could feed through the [`ReactDOMServer.renderToString()`](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostring) or [`ReactDOMServer.renderToStaticMarkup()`](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostaticmarkup) functions?

BootstrapResult could then have a new "result" property, which is just whatever the render function returns.

A consumer already has the "initialState" option to influence what is in the store, and thus what state the components should be in when they are rendered.

**Comment by jokeyrhyme** [comment]
If I just use the `createLocation()` function from the "history" package, I get this:

> ERROR: 'Warning: [history] Using createLocation without a history instance is deprecated; please use history.createLocation instead'

Which means we need the `history` from the BootstrapResult _before_ we can insert a new location created via `history.createLocation()`.
